name: Generate Snake Animation

on:
  schedule: # প্রতি 12 ঘন্টায় auto run
    - cron: "0 */12 * * *"
  workflow_dispatch: # manual run করার option

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: shaidmeheraj   # তোমার সঠিক GitHub username
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
